# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har

import sys
from pathlib import Path

import pytest
from httprunner import Parameters

sys.path.insert(0, str(Path(__file__).parent.parent))

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login_test import TestCaseMubuLogin as MubuLogin


class TestCaseCreateDoc(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "docTitle": "${gen_doc_titles(2)}",
                "phone-password": "${parameterize(data/accounts.csv)}",
            }
        )
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("testcase description")
        .variables(
            **{
                "memberId": "${gen_member_id()}",
                "host": "mubu.com",
                "phone": "18613143458",
                "password": "msFrwx$!kt3RTRq@Q*pV",
                "docTitle": "${gen_random_title()}",
            }
        )
        .base_url("https://$host")
        .verify(False)
        .export("docTitle", "docID")
    )

    teststeps = [
        Step(
            RunTestCase("login")
            .call(MubuLogin)
            .export("data_unique_id", "JwtToken", "user_persistence")
        ),
        Step(
            RunRequest("/api/list/create_doc")
            .post("/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "17",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "SLARDAR_WEB_ID": "8365d4b0-786b-4509-a35d-5102202f6f75",
                    "mubu_inner": "1",
                }
            )
            .with_data({"folderId": "0", "type": "0"})
            .extract()
            .with_jmespath("body.data.id", "docID")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc${docID}")
            .get("/doc${docID}")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "SLARDAR_WEB_ID": "8365d4b0-786b-4509-a35d-5102202f6f75",
                    "mubu_inner": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .options("https://api2.${host}/v3/api/user/current_user")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .options("https://api2.${host}/v3/api/document/get")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .options("https://api2.${host}/v3/api/user/current_level")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .post("https://api2.${host}/v3/api/user/current_user")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "3052befa-0cd3-4e21-8cb3-02c7f1fcb232",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .post("https://api2.${host}/v3/api/document/get")
            .with_headers(
                **{
                    "content-length": "23",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "75d37b87-96a7-4b11-9301-5bf4999fcb2b",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"docId": "${docID}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.${host}/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "604975c0-5a7c-4b32-a641-a993dab0ab98",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"document_id": "${docID}"})
            .extract()
            .with_jmespath("body.data.id", "userId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .options("https://api2.${host}/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.${host}/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "1e2de244-914b-4c02-889c-28d8064c501c",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .options("https://api2.${host}/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("https://api2.${host}/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.${host}/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "cf2af2df-96ba-4875-bda1-98fbbd6274e3",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.${host}/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "215f81a3-a409-47b4-ab4d-fe46522bdea5",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "${memberId}", "documentId": "${docID}"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "${memberId}", "documentId": "${docID}"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "members:${memberId}:1602915036641",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "8dd0d063-e99f-46c5-8541-45c7ed93675a",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .options("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,member-id,request-id,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "513",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:6",
                    "x-request-id": "fddbac5a-e710-4a56-a971-df263c9d68fa",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 6,
                    "requestId": "MESSAGE:${userId}:${memberId}:6",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 0,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "$docTitle",
                                    "original": "",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "458",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:8",
                    "x-request-id": "632313f3-2a91-4975-8c38-c29626ee6efc",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 8,
                    "requestId": "MESSAGE:${userId}:${memberId}:8",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "3PRB3hFXfZ",
                                                "text": "",
                                                "modified": 1602915043783,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "505",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:10",
                    "x-request-id": "c97cdfea-8933-469f-ac21-a63b8804261b",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 10,
                    "requestId": "MESSAGE:${userId}:${memberId}:10",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 2,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "3PRB3hFXfZ",
                                                "text": "<span>111</span>",
                                                "modified": 1602915044782,
                                            },
                                            "original": {
                                                "id": "3PRB3hFXfZ",
                                                "text": "",
                                                "modified": 1602915043783,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "460",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:12",
                    "x-request-id": "98680e5d-5e81-44d2-9aae-1f15bd81b714",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 12,
                    "requestId": "MESSAGE:${userId}:${memberId}:12",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "DkoagedPfV",
                                                "text": "",
                                                "modified": 1602915045430,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "503",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:13",
                    "x-request-id": "5064ff01-f7fe-486e-8180-bc343640a299",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:${userId}:${memberId}:13",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "DkoagedPfV",
                                                "text": "<span>2</span>",
                                                "modified": 1602915045836,
                                            },
                                            "original": {
                                                "id": "DkoagedPfV",
                                                "text": "",
                                                "modified": 1602915045430,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "519",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:15",
                    "x-request-id": "3d7ebeef-b899-44d2-81a0-125166b4e0e8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:${userId}:${memberId}:15",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "DkoagedPfV",
                                                "text": "<span>222</span>",
                                                "modified": 1602915046146,
                                            },
                                            "original": {
                                                "id": "DkoagedPfV",
                                                "text": "<span>2</span>",
                                                "modified": 1602915045836,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/get_recent_list")
            .options("https://api2.${host}/v3/api/document/get_recent_list")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/get_recent_list")
            .post("https://api2.${host}/v3/api/document/get_recent_list")
            .with_headers(
                **{
                    "content-length": "42",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-request-id": "1ebe04c1-252c-4219-9cfb-5ab7420d675e",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"documentId": "${docID}", "keywords": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "227",
                    "member-id": "${memberId}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:18",
                    "x-request-id": "f916ac54-2af5-41c1-a9ce-f5b1db6863f7",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 18,
                    "requestId": "MESSAGE:${userId}:${memberId}:18",
                    "token": "${docID}",
                    "data": {},
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.476",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/doc${docID}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "mubu_inner": "1",
                    "SLARDAR_WEB_ID": "a87ef0b2-2e21-455f-ae21-f4b4e8bc43b2",
                    "_gat_UA-77727571-3": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "mubu_inner": "1",
                    "SLARDAR_WEB_ID": "a87ef0b2-2e21-455f-ae21-f4b4e8bc43b2",
                    "_gat_UA-77727571-3": "1",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "mubu_inner": "1",
                    "SLARDAR_WEB_ID": "a87ef0b2-2e21-455f-ae21-f4b4e8bc43b2",
                    "_gat_UA-77727571-3": "1",
                }
            )
            .with_data({"folderId": "0", "sort": "name", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "${data_unique_id}",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "Jwt-Token": "${JwtToken}",
                    "user_persistence": "${user_persistence}",
                    "mubu_inner": "1",
                    "SLARDAR_WEB_ID": "a87ef0b2-2e21-455f-ae21-f4b4e8bc43b2",
                    "_gat_UA-77727571-3": "1",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateDoc().test_start()
